import React from 'react';
// import { Link } from 'react-router-dom';
import Titlebar from '../../Components/Common/Titlebar';
import '../../Assets/css/table.css';
import InputComponent from '../../Components/Common/InputComponent';
import ButtonComponent from '../../Components/Common/ButtonComponent';
import LabelComponent from '../../Components/Common/LabelComponent';


const SalesSlip = () => {
    const title = 'タイトルタイトル';
    return (
        <>
            <Titlebar title={title} />
                        {/* first button line  */}
                        <div className='flex justify-between' style={{width:'70%'}}>
                            <div className='flex mt-10 w-1/2' >
                                <ButtonComponent children={'Purchase request form for recycling shops'} style={{backgroundColor:'#9bd195',}}/>
                                <ButtonComponent children={'request application'} style={{backgroundColor:'#9bd195',marginLeft:'30px'}} />
                            </div>
                            <div className='flex justify-end mt-10 w-1/2' >
                                <ButtonComponent children={'sales table'} style={{backgroundColor:'#424242',}}/>
                                <ButtonComponent children={'vendor assessment sheet'} style={{backgroundColor:'transparent',border:'1px solid #424242',color:'#424242',marginLeft:'30px'}} />
                                <ButtonComponent children={'Yahoo Auction'} style={{backgroundColor:'transparent',border:'1px solid #424242',color:'#424242',marginLeft:'30px'}} />
                            </div>
                        </div>

                        {/* second button line  */}
                        <div className='flex' style={{width:'70%'}}>
                            <div className='flex justify-end mt-10' >
                                <ButtonComponent children={'Purchase request form for recycling shops'} style={{backgroundColor:'#9bd195',}}/>
                                <ButtonComponent children={'request application'} style={{backgroundColor:'#9bd195',marginLeft:'30px'}} />
                            </div>
                        </div>

                        {/*  Tabe*/}
                        <div className='mt-10 pl-10 pr-10 pb-20 w-full flex'>
                            <table className='text-center w-full'>
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th width='10%'>Last Name</th>
                                        <th width='10%'>Points</th>
                                        <th width='10%'>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th width='10%'>Points</th>
                                        <th>Points</th>
                                        <th width='10%'>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th width='10%'>Points</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                </tbody>

                            </table>
                        </div>
        </>
    );
};

export default SalesSlip;