import React from 'react';
// import { Link } from 'react-router-dom';
import Titlebar from '../../Components/Common/Titlebar';
import '../../Assets/css/showtable.css'


const MonthlyIncome = () => {
    const title = 'タイトルタイトル';
    return (
        <>
            <Titlebar title={title} />
            <div className='flex justify-around mt-10'>
                <div className='flex'>
                    <button type="button"
                        className="mr-10  py-1 min-w-[160px] text-[#70685a] rounded-full tracking-wider font-bold outline-none border border-[#70685a] ">Purple</button>
                    <button type="button"
                        className=" mr-3 py-1 min-w-[160px] text-[#70685a] rounded-full tracking-wider font-bold outline-none border border-[#70685a] ">Purple</button>
                </div>
                <h2 className="text-[#70685a] text-center text-2xl font-bold flex justify-center">Monthly Income</h2>
                <div className='flex justify-around'>
                    <button type="button"
                        className=" py-1 min-w-[160px] text-[#70685a] rounded-full tracking-wider font-bold outline-none border border-[#70685a] ">Purple</button>
                    <button type="button"
                        className="ml-10 py-1 min-w-[160px] text-[#70685a] rounded-full tracking-wider font-bold outline-none border border-[#70685a] ">Purple</button>
                </div>
            </div>
            {/*  */}
            <div className='flex mt-5' style={{ paddingLeft: '30%' }}>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>this year</div>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>this monthy</div>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>last monthy</div>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>today</div>
            </div>
            {/*  */}
            <div className='flex mt-3' style={{ paddingLeft: '30%' }}>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>
                    <input type="date" />
                </div>
                <div className=' text-[#70685a] px-2 mr-2'>
                    <label className="text-[#70685a] font-bold mb-2 block text-center !mb-0">~</label>
                </div>
                <div className='border border-[#70685a] text-[#70685a] px-2 mr-2'>
                    <input type="date" />
                </div>
                <div className=' text-[#70685a] px-2 mr-5'>
                    <label className="text-[#70685a] font-bold mb-2 block text-center !mb-0">Search with this condition</label>
                </div>
                <div className=' text-[#70685a] px-2 mr-2'>
                    < button type="button" className="w-20 px-3 py-1 font-bold tracking-wide rounded-lg justify-center text-white bg-[#a3a1c8] hover:bg-blue-700 focus:outline-none">
                        LOGIN
                    </button>
                </div>
                <div className=' text-[#70685a] px-2 mr-5'>
                    <label className="text-[#70685a] mb-2 block text-center !mb-0">and search</label>
                </div>
            </div>
            {/*  */}
            <div className='flex mt-5'>
                <div className='w-20' style={{ marginLeft: '10%' }}>
                    <div className='text-center text-[#70685a] text-[15px] font-bold '>cost</div>
                    <div className='border border-[#70685a] text-[#70685a] px-2 text-center'>99999yen</div>
                </div>
                <div className='text-center text-[#70685a] text-[15px] mr-5 mt-8' style={{ marginLeft: '40%' }}>
                    <label>(asd)</label>
                </div>
                <div className='w-20 mr-10'>
                    <div className='text-center text-[#70685a] text-[15px] font-bold'>cost</div>
                    <div className='border border-[#70685a] text-[#70685a] px-2 text-center'>99999yen</div>
                </div>
                <div className='w-20'>
                    <div className='text-center text-[#70685a] text-[15px] font-bold'>cost</div>
                    <div className='border border-[#70685a] text-[#70685a] px-2 text-center'>99999yen</div>
                </div>
            </div>
            {/*  Tabe*/}
            <div className='pl-10 pr-10 pb-20 w-full flex'>
                <div className='mt-5 w-20 mr-5'>
                    < button type="button" className="w-20 text-[15px] font-bold tracking-wide rounded-sm justify-center text-white bg-[#fe5d5c] hover:bg-blue-700 focus:outline-none">
                        LOGIN
                    </button>
                    < button type="button" className="w-20 mt-3 text-[15px] font-bold tracking-wide rounded-sm justify-center text-white bg-[#76cc90] hover:bg-blue-700 focus:outline-none">
                        LOGIN
                    </button>
                </div>
                <table className='text-center w-full'>
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                    </tbody>

                </table>
            </div>
        </>
    );
};

export default MonthlyIncome;