import React from 'react';
// import { Link } from 'react-router-dom';
import Titlebar from '../../Components/Common/Titlebar';
import '../../Assets/css/showtable.css';
import '../../Assets/css/firstTd.css';
import '../../Assets/css/lastTd.css';
import InputComponent from '../../Components/Common/InputComponent';
// import ButtonComponent from '../../Components/Common/ButtonComponent';
import LabelComponent from '../../Components/Common/LabelComponent';


const WholeSalerShippingList = () => {
    const title = 'タイトルタイトル';
    return (
        <>
            <Titlebar title={title} />
            <div className="bg-[trasparent] font-[sans-serif]">
                <div className='flex justify-center'>
                    <div className="w-full pt-3" style={{ maxWidth: '80em' }}>


                        <div className='flex justify-around mt-10' >
                            <h2 className="text-[#70685a] text-center text-2xl font-bold flex justify-center">Whole Saler Shipping List</h2>
                        </div>

                        {/*  */}
                        <div className='flex mt-3 justify-center pr-40 pl-40'>
                            <div className=' px-2 mr-2 text-center'>
                                <LabelComponent value={'adf'} />
                                <div><input type="date" /></div>
                            </div>
                            <div className=' text-[#70685a] px-2 mr-2'>
                                <div className='text-center'>
                                    <LabelComponent value={'adf'} />
                                </div>
                                <InputComponent style={{ height: '30px',}} />
                            </div>
                            <div className=' text-[#70685a] px-2 mr-2'>
                                <div className='text-center'>
                                    <LabelComponent value={'adf'} />
                                </div>
                                <InputComponent style={{ height: '30px',}} />
                            </div>
                            <div className=' text-[#70685a] px-2 mr-2'>
                                <div className='text-center'>
                                    <LabelComponent value={'adf'} />
                                </div>
                                <InputComponent style={{ height: '30px',}} />
                            </div>


                            <div className=' text-[#70685a] px-2 mr-5' style={{ display: 'flex', alignItems: 'end' }}>
                                <label className="text-[#70685a] font-bold block text-center ">Search with </label>
                            </div>
                            <div className=' text-[#70685a] px-2 mr-2' style={{ display: 'flex', alignItems: 'end' }}>
                                < button type="button" style={{ display: 'flex', alignItem: 'end' }} className="flex align-end w-20 px-3 py-1 font-bold rounded-md tracking-wide justify-center text-white bg-[#a3a1c8] hover:bg-blue-700 focus:outline-none">
                                    LOGIN
                                </button>
                            </div>
                            <div className=' text-[#70685a] px-2 mr-5' style={{ display: 'flex', alignItems: 'end' }}>
                                <label className="text-[#70685a] mb-2 block text-center">and search</label>
                            </div>
                        </div>

                        {/*  Tabe*/}
                        <div className='mt-10 pl-10 pr-10 pb-20 w-full flex'>
                            <table className='text-center w-full'>
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Last Name</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                        <th>Points</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                    <tr>
                                        <td>Jill</td>
                                        <td>Smith</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                        <td>50</td>
                                    </tr>
                                    <tr>
                                        <td>Eve</td>
                                        <td>Jackson</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                        <td>94</td>
                                    </tr>
                                    <tr>
                                        <td>Adam</td>
                                        <td>Johnson</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                        <td>67</td>
                                    </tr>
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default WholeSalerShippingList;